[package]
name = "mnm-dlmm"
version = "0.1.0"
edition.workspace = true
description = "Jupiter AMM adapter for MnM DLMM protocol"
license = "Apache-2.0"

[dependencies]
jupiter-amm-interface = { workspace = true }
solana-sdk = { workspace = true }
bytemuck = { workspace = true }
borsh = { workspace = true }
anyhow = { workspace = true }
rust_decimal = "1.36"
