#!/bin/sh

# SPL
solana account -o tests/fixtures/accounts/Gb7m4daakbVbrFLR33FKMDVMHAprRZ66CSYt4bpFwUgS/SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy.json --output json SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy
solana account -o tests/fixtures/accounts/Gb7m4daakbVbrFLR33FKMDVMHAprRZ66CSYt4bpFwUgS/EmiU8AQkB2sswTxVB6aCmsAJftoowZGGDXuytm6X65R3.json --output json EmiU8AQkB2sswTxVB6aCmsAJftoowZGGDXuytm6X65R3
# Sanctum SPL
solana account -o tests/fixtures/accounts/Gb7m4daakbVbrFLR33FKMDVMHAprRZ66CSYt4bpFwUgS/SP12tWFxD9oJsVWNavTTBZvMbA6gkAmxtVgxdqvyvhY.json --output json SP12tWFxD9oJsVWNavTTBZvMbA6gkAmxtVgxdqvyvhY
solana account -o tests/fixtures/accounts/Gb7m4daakbVbrFLR33FKMDVMHAprRZ66CSYt4bpFwUgS/Cn5fegqLh8Fmvffisr4Wk3LmuaUgMMzTFfEuidpZFsvV.json --output json Cn5fegqLh8Fmvffisr4Wk3LmuaUgMMzTFfEuidpZFsvV
# Sanctum SPL Multi
solana account -o tests/fixtures/accounts/Gb7m4daakbVbrFLR33FKMDVMHAprRZ66CSYt4bpFwUgS/SPMBzsVUuoHA4Jm6KunbsotaahvVikZs1JyTW6iJvbn.json --output json SPMBzsVUuoHA4Jm6KunbsotaahvVikZs1JyTW6iJvbn
solana account -o tests/fixtures/accounts/Gb7m4daakbVbrFLR33FKMDVMHAprRZ66CSYt4bpFwUgS/HxBTMuB7cFBPVWVJjTi9iBF8MPd7mfY1QnrrWfLAySFd.json --output json HxBTMuB7cFBPVWVJjTi9iBF8MPd7mfY1QnrrWfLAySFd
# Marinade
solana account -o tests/fixtures/accounts/Gb7m4daakbVbrFLR33FKMDVMHAprRZ66CSYt4bpFwUgS/MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD.json --output json MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD
solana account -o tests/fixtures/accounts/Gb7m4daakbVbrFLR33FKMDVMHAprRZ66CSYt4bpFwUgS/4PQH9YmfuKrVyZaibkLYpJZPv2FPaybhq2GAuBcWMSBf.json --output json 4PQH9YmfuKrVyZaibkLYpJZPv2FPaybhq2GAuBcWMSBf
# Lido
solana account -o tests/fixtures/accounts/Gb7m4daakbVbrFLR33FKMDVMHAprRZ66CSYt4bpFwUgS/CrX7kMhLC3cSsXJdT7JDgqrRVWGnUpX3gfEfxxU2NVLi.json --output json CrX7kMhLC3cSsXJdT7JDgqrRVWGnUpX3gfEfxxU2NVLi
solana account -o tests/fixtures/accounts/Gb7m4daakbVbrFLR33FKMDVMHAprRZ66CSYt4bpFwUgS/CHZNLhDXKrsXBmmv947RFciquwBsn2NdABmhpxoX3wgZ.json --output json CHZNLhDXKrsXBmmv947RFciquwBsn2NdABmhpxoX3wgZ